[tool.isort]
multi_line_output = 5
line_length       = 88

[tool.pytest.ini_options]
testpaths    = ["tests"] # Search for tests in tests/
asyncio_mode = 'auto'

[tool.coverage.run]
omit = ["venv/*"] # when running pytest --cov, dont report coverage in venv directories
